//-----------------------------------------------
//
//	This file is part of the Siv3D Engine.
//
//	Copyright (c) 2008-2020 Ryo Suzuki
//	Copyright (c) 2016-2020 OpenSiv3D Project
//
//	Licensed under the MIT License.
//
//-----------------------------------------------

# pragma once
# include <ThirdParty/SFMT/SFMT.h>
# include "Types.hpp"
# include "Number.hpp"
# include "HardwareRNG.hpp"

namespace s3d
{
	namespace PRNG
	{
		/// <summary>
		/// SFMT 19937 / Pseudo random number generator
		/// Result: 64-bit value
		/// Period: 2^19937-1
		/// Size: 2,512 bytes
		/// </summary>
		class SFMT19937_64
		{
		public:

			using State_t = SFMT_T;

		private:

			State_t m_state;

		public:

			static constexpr size_t SeedSequencCount = 16;

			/// <summary>
			/// 生成される整数値の型
			/// The integral type generated by the engine
			/// </summary>
			using result_type = uint64;

			/// <summary>
			/// 乱数エンジンを作成し、内部状態を非決定的な乱数で初期化します。
			/// Constructs the engine and initializes the state with non-deterministic random numbers
			/// </summary>
			SFMT19937_64()
			{
				HardwareRNG rng;

				uint32 keys[SeedSequencCount];

				for (auto& key : keys)
				{
					key = rng();
				}

				::sfmt_init_by_array(&m_state, keys, static_cast<int32>(SeedSequencCount));
			}

			/// <summary>
			/// 乱数エンジンを作成し、内部状態を初期化します。
			/// Constructs the engine and initializes the state.
			/// </summary>
			/// <param name="seed">
			/// 内部状態の初期化に使われるシード値
			/// seed value to use in the initialization of the internal state
			/// </param>
			explicit SFMT19937_64(uint64 seed)
			{
				this->seed(seed);
			}

			explicit SFMT19937_64(const std::array<uint64, SeedSequencCount>& seeds)
			{
				this->seed(seeds);
			}

			void seed(uint64 seed);

			void seed(const std::array<uint64, SeedSequencCount>& seeds);

			/// <summary>
			/// 生成される乱数の最小値を返します。
			/// Returns the minimum value potentially generated by the random-number engine
			/// </summary>
			/// <returns>
			/// 生成される乱数の最小値
			/// The minimum potentially generated value
			/// </returns>
			[[nodiscard]]
			static constexpr result_type min() noexcept
			{
				return Smallest<result_type>;
			}

			/// <summary>
			/// 生成される乱数の最大値を返します。
			/// Returns the maximum value potentially generated by the random-number engine.
			/// </summary>
			/// <returns>
			/// 生成される乱数の最大値
			/// The maximum potentially generated value
			/// </returns>
			[[nodiscard]]
			static constexpr result_type max() noexcept
			{
				return Largest<result_type>;
			}

			/// <summary>
			/// 乱数を生成します。
			/// Generates a pseudo-random value.
			/// </summary>
			/// <returns>
			/// 生成された乱数
			/// A generated pseudo-random value
			/// </returns>
			result_type operator()() noexcept
			{
				return ::sfmt_genrand_uint64(&m_state);
			}

			/// <summary>
			/// [0, 1) の範囲の乱数を生成します。
			/// Generates a pseudo-random value in [0, 1)
			/// </summary>
			/// <returns>
			/// 生成された乱数
			/// A generated pseudo-random value
			/// </returns>
			double generateReal() noexcept
			{
				return ::sfmt_genrand_res53(&m_state);
			}

			[[nodiscard]]
			constexpr const State_t& serialize() const noexcept
			{
				return m_state;
			}

			constexpr void deserialize(const State_t& data) noexcept
			{
				m_state = data;
			}
		};
	}
}
